<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerSdouYt3\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerSdouYt3/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerSdouYt3.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerSdouYt3\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerSdouYt3\App_KernelDevDebugContainer([
    'container.build_hash' => 'SdouYt3',
    'container.build_id' => 'd6568857',
    'container.build_time' => 1722162206,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerSdouYt3');
